apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-name
data:
  mysqldb.properties: |
    mysql.dbname=mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username.properties: c3ByaW5nYm9vdEBzcWxkYXRhYmFzZXNwcmluZ2Jvb3Q=
  password.properties: Nzg2TXlzcWwxMTAu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-service
  labels:
    app: po-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: po-service
  template:
    metadata:
      labels:
        app: po-service
    spec:
      volumes:
      - name: mysqlcm
        configMap:
          name: mysql-db-name
      - name: mysqlse
        secret:
          secretName: mysql-secret
      containers:
      - name: po-service
        image: springboot.azurecr.io/po-service:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: mysqlcm
          mountPath: /etc/config
        - name: mysqlse
          mountPath: /etc/vol-secrets
---
kind: Service
apiVersion: v1
metadata:
  name: po-service
spec:
  type: LoadBalancer
  selector:
    app: po-service
  ports:
  - name: 80-tcp
    protocol: TCP
    port: 80
    targetPort: 8080
